### ISSUE TITLE
Make the program take only valid inputs.

### ISSUE THREAD

**Issue by noturshek** [itsabhianant/rock_paper_scissors#2]
The program at this point of time takes any input rather than taking r for rock, s for scissors, and p for papers. Make changes such that if the player gives any input to the program rather than r,p,s it shows the users that it is an invalid input and the program start again.

Also if you are working on the issue please let me know so that I can assign it to you.

**Comment by ghost** [comment]
Pull request fix #3 adds validation for inputs to resolve issue #2
